# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/auguste/prog/batsim

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/auguste/prog/batsim

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/auguste/prog/batsim/CMakeFiles /home/auguste/prog/batsim/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/auguste/prog/batsim/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named batsim

# Build rule for target.
batsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 batsim
.PHONY : batsim

# fast build rule for target.
batsim/fast:
	$(MAKE) -f CMakeFiles/batsim.dir/build.make CMakeFiles/batsim.dir/build
.PHONY : batsim/fast

#=============================================================================
# Target rules for targets named parallel_task

# Build rule for target.
parallel_task: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parallel_task
.PHONY : parallel_task

# fast build rule for target.
parallel_task/fast:
	$(MAKE) -f CMakeFiles/parallel_task.dir/build.make CMakeFiles/parallel_task.dir/build
.PHONY : parallel_task/fast

batsim.o: batsim.c.o
.PHONY : batsim.o

# target to build an object file
batsim.c.o:
	$(MAKE) -f CMakeFiles/batsim.dir/build.make CMakeFiles/batsim.dir/batsim.c.o
.PHONY : batsim.c.o

batsim.i: batsim.c.i
.PHONY : batsim.i

# target to preprocess a source file
batsim.c.i:
	$(MAKE) -f CMakeFiles/batsim.dir/build.make CMakeFiles/batsim.dir/batsim.c.i
.PHONY : batsim.c.i

batsim.s: batsim.c.s
.PHONY : batsim.s

# target to generate assembly for a file
batsim.c.s:
	$(MAKE) -f CMakeFiles/batsim.dir/build.make CMakeFiles/batsim.dir/batsim.c.s
.PHONY : batsim.c.s

parallel_task.o: parallel_task.c.o
.PHONY : parallel_task.o

# target to build an object file
parallel_task.c.o:
	$(MAKE) -f CMakeFiles/parallel_task.dir/build.make CMakeFiles/parallel_task.dir/parallel_task.c.o
.PHONY : parallel_task.c.o

parallel_task.i: parallel_task.c.i
.PHONY : parallel_task.i

# target to preprocess a source file
parallel_task.c.i:
	$(MAKE) -f CMakeFiles/parallel_task.dir/build.make CMakeFiles/parallel_task.dir/parallel_task.c.i
.PHONY : parallel_task.c.i

parallel_task.s: parallel_task.c.s
.PHONY : parallel_task.s

# target to generate assembly for a file
parallel_task.c.s:
	$(MAKE) -f CMakeFiles/parallel_task.dir/build.make CMakeFiles/parallel_task.dir/parallel_task.c.s
.PHONY : parallel_task.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... batsim"
	@echo "... edit_cache"
	@echo "... parallel_task"
	@echo "... rebuild_cache"
	@echo "... batsim.o"
	@echo "... batsim.i"
	@echo "... batsim.s"
	@echo "... parallel_task.o"
	@echo "... parallel_task.i"
	@echo "... parallel_task.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

