#!/bin/sh

set -e

if [ "$IFACE" != "myri0" ]; then
    exit 0
fi

SHORTNAME=$(hostname -s)

/etc/init.d/mx start

/sbin/ifconfig "$IFACE" $(gethostip -d "$SHORTNAME-$IFACE") netmask 255.255.240.0 up
