#!/bin/sh

# MANAGED BY PUPPET
# Module:: env::std::net_access
#

/sbin/iptables-restore <<EOF
*filter

:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]

#Log outgoing traffic to NAT
# ACCEPT even if it s default policy : Avoid having these destinations in the logs
-A OUTPUT -d 127.0.0.1 -j ACCEPT
-A OUTPUT -d 172.16.0.0/12 -j ACCEPT
-A OUTPUT -d 10.0.0.0/8 -j ACCEPT
-A OUTPUT -d 192.168.4.0/24 -j ACCEPT
-A OUTPUT -d 192.168.66.0/24 -j ACCEPT
# Multicast ganglia
-A OUTPUT -d 239.2.11.71/32 -j ACCEPT

# Log everything else : it's going outside g5k
-A OUTPUT -m conntrack --ctstate NEW -j LOG --log-level 7 --log-uid --log-prefix "outgoing traffic "
COMMIT
EOF
