#!/bin/sh
set -e
BRIDGE="br0"
if [ -z "$SUDO_USER" ]; then
  echo "error: SUDO_USER is not set"
  exit 1
fi
TAPDEV=`/usr/sbin/tunctl -b -u $SUDO_USER`
/sbin/brctl addif $BRIDGE $TAPDEV
ip link set $TAPDEV up
echo $TAPDEV >> /var/lib/oar/tap_devices_for_user_$SUDO_USER
chown oar:oar /var/lib/oar/tap_devices_for_user_$SUDO_USER
echo $TAPDEV
